melody:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.120.32.139
    port: 3306
    database: melody
    username: dmsTest
    password: Ecs@123aaa
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t933NKHGBJiMPyYfkVN
    access-key-secret: o3bm1rdSivhYRsBl5KlUqXK5uZnaPM
    bucket-name: candour-sky-takeout