server:
  port: 8080


spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${melody.datasource.driver-class-name}
      url: jdbc:mysql://${melody.datasource.host}:${melody.datasource.port}/${melody.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${melody.datasource.username}
      password: ${melody.datasource.password}


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.melody.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


logging:
  level:
    com:
      melody:
        mapper: debug
        service: info
        controller: info


melody:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    teacher-secret-key: itcast
    # 设置jwt过期时间
    teacher-ttl: 7200000
    # 设置前端传递过来的令牌名称
    teacher-token-name: token
  alioss:
    endpoint: ${melody.alioss.endpoint}
    access-key-id: ${melody.alioss.access-key-id}
    access-key-secret: ${melody.alioss.access-key-secret}
    bucket-name: ${melody.alioss.bucket-name}
